[workspace]
members = [
    "xtask",
    "libs/stdio",
    "platforms/qemu-virt",
    "platforms/qemu-virt-ld",
    "platforms/qemu-sifive_u",
    "platforms/qemu-sifive_u-ld",
    "platforms/guest",
    "apps/app1",
    "apps/app2",
    "obj",
]
default-members = ["xtask"]
