[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.2", features = ["derive"] }
command-ext = { git = "https://github.com/YdrMaster/command-ext.git", rev = "f25befb" }
once_cell = "1.14"
