[package]
name = "qemu-sifive_u"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sbi-rt = { version = "0.0.2", features = ["legacy"] }
riscv = "0.9.0"

platform = { path = "../platform" }
